enum eStringTable {

    MZero,
    MOk,
    MCancel,
    MBtnPresets,
    MBtnAdvanced,
    MBtnBatch,
    MBtnRetry,
    MBtnSettings,
    MBtnClose,
    MBtnClear,
    MError,
    MWarning,
    MQuoteSearch,
    MQuoteReplace,
    MEllipsis,
    MLeftBracket,
    MRightBracket,
    MKB,
    MMB,

    MStructuredFile,
    MRawEdit,

    MCopy,
    MCopyOneTo,
    MCopyManyTo,
    MDelete,
    MDeleteOne,
    MDeleteMany,
    MSaveChanges,

    MExportPrettyPrint,
    MEditPrettyPrint,
    MIndent,
    MSaveUnixEOL,

    MInvalidNumber,
    MOpenError,
    MSaveError,
    MParseError,
};
